/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionproyectos.vista;

import PatronesDiseño.PrincipalVisitador;
import gestionproyectos.controlador.PrincipalController;
import gestionproyectos.modelo.TareaInfo;
import gestionproyectos.modelo.Tareas;
import java.util.List;

/**
 *
 * @author gianlucasorem
 */
public class controlar_tiempoTotalPro extends javax.swing.JPanel {
    private int cont;

    /**
     * Creates new form controlar_tiempoTotalPro
     */
    public controlar_tiempoTotalPro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TXT_TIME = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("EL TIEMPO TOTAL INVERTIDO EN ESTE PROYECTO FUE DE:");

        TXT_TIME.setText("jLabel2");

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(TXT_TIME))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jButton1)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(TXT_TIME)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   visitador.CambiarTarjetaB("TareaControlada");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TXT_TIME;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
   private PrincipalVisitador visitador;

    public void setVisitador(PrincipalVisitador visitador) {
        this.visitador = visitador;
    }
    
    public void cargarInformacion(){
    this.cont=0;
    List<Tareas> tareasProyecto = PrincipalController.getInstance().cargarTareasControlar();
    List<TareaInfo> tareasInfo = PrincipalController.getInstance().getTotasTareasInfo();
    
        for (int i = 0; i < tareasProyecto.size(); i++) {
            
            for (int j = 0; j < tareasInfo.size(); j++) {
                if(tareasProyecto.get(i).getIdTarea()==tareasInfo.get(j).getIdtarea()){
                this.cont= this.cont+tareasInfo.get(j).getTiempoTotal();
                } 
                
            }
            
            
        }
        
        
        String contText = Integer.toString(this.cont);
        TXT_TIME.setText(contText+"s");
    
    }
   
   
}
